name: build

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIMEOUT: ${{ vars.TIMEOUT }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install requests
      - run: python src/init.py

      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - run: npm run build

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "⚡build: $(date +%Y/%m/%d)" || echo "No changes to commit"
          git push
